services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001
    env_file:
      - .env
    # command: env # Print env on console
    depends_on:
      - mongo
  mongo:
    image: mongodb/mongodb-community-server:latest
    # restart: always
    volumes:
      - mongo-data:/data/db
    command: mongod --quiet # Hides snapshots logs in console
    # healthcheck:
    #   test: ['CMD', 'mongo', '--eval', "db.adminCommand('ping')"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
volumes:
  mongo-data:
