services:
  # inx application configuration
  inx-srvc:
    build:
      context: .
      dockerfile: Dockerfile
    image: inx-srvc:${INX_IMAGE_TAG}
    container_name: inx-srvc-server
    depends_on:
      inx-srvc-database:
        condition: service_healthy
        restart: true
    env_file:
      - .env
    ports:
      - 3001:3001

  # database service setup
  inx-srvc-database:
    image: mongodb/mongodb-community-server:5.0.27-ubi8
    container_name: inx-srvc-database
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminInxPass
      - MONGO_INITDB_DATABASE=insightxCaLocal
    volumes:
      - inx-srvc-storage:/data/db
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb://admin:adminInxPass@localhost:27017/admin --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

# Create volume
volumes:
  inx-srvc-storage:
    name: inx-srvc-storage
