name: Static Code CI

# Controls when the workflow will run
on:
  pull_request:
    branches: ['main']
  push:
    branches: ['development', 'main']

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.2

      # Sets up pnpm package of version
      - name: Install pnpm
        run: npm install -g pnpm@10.4.1

      - name: Install Dependencies
        run: pnpm install

      - name: Run Lint
        run: pnpm run lint

      - name: CI Completed
        run: echo CI Completed

      # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
